### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by lixryjz** [ZhuoyunZhong/Mobile-Robot-Demo-with-Unity-ROS#1]
as you can see,I run the demo and meet some problems
the first is "run the server.launch"
![1](https://user-images.githubusercontent.com/95114989/171146951-8cb6b2a3-67fe-4855-b6b7-fbe220ec12e5.jpg)
the second is publish command ,but the robot don't move
![2](https://user-images.githubusercontent.com/95114989/171147213-d0ff21ad-1322-4c73-89e6-d6ee43e96e06.jpg)
and in uinty i get a wanining!
![3](https://user-images.githubusercontent.com/95114989/171147333-6d663026-ed2b-4682-963c-04e497d74a0f.jpg)

**Comment by lixryjz** [comment]
I hope you can tell me ,thanks for a lot

**Comment by ZhuoyunZhong** [comment]
> as you can see,I run the demo and meet some problems the first is "run the server.launch" ![1](https://user-images.githubusercontent.com/95114989/171146951-8cb6b2a3-67fe-4855-b6b7-fbe220ec12e5.jpg) the second is publish command ,but the robot don't move ![2](https://user-images.githubusercontent.com/95114989/171147213-d0ff21ad-1322-4c73-89e6-d6ee43e96e06.jpg) and in uinty i get a wanining! ![3](https://user-images.githubusercontent.com/95114989/171147333-6d663026-ed2b-4682-963c-04e497d74a0f.jpg)

Hi, the original package is outdated so there could be some version confliction issue. I have updated everything to up-to-date version and add one more tutorial on using ROS navigation packages. Please try it and let me know if the problem persists. I will close this issue for now.
