### ISSUE TITLE
The type or namespace name 'Rosgraph' does not exist in the namespace 'RosMessageTypes' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by robot-WT** [ZhuoyunZhong/Mobile-Robot-Demo-with-Unity-ROS#2]
I have encountered the following problem. I am not familiar with C #. Can you help me take a look?
![image](https://github.com/ZhuoyunZhong/Mobile-Robot-Demo-with-Unity-ROS/assets/78524771/bb05247d-fec6-42a7-98b8-6eba77a2f19e)

**Comment by ZhuoyunZhong** [comment]
I could not reproduce the error. Just to confirm, did you install ROS-TCP-Connector and URDF-Importer?

> https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/quick_setup.md

Could you also show me what version you are using?

**Comment by robot-WT** [comment]
Thank you for your reply. I have resolved this issue by updating the version of ROS-TCP Connector to 0.7.0
